### ISSUE TITLE
Using Sam when deploying to aws lambda i am facing this error when using flask-lambda package

### ISSUE THREAD

**Issue by Rumman001** [sivel/flask-lambda#11]
[ERROR] KeyError: 'SERVER_NAME'Traceback (most recent call last):  File "/var/task/flask_lambda.py", line 97, in __call__    return super(FlaskLambda, self).__call__(event, context)  File "/var/task/flask/app.py", line 2464, in __call__    return self.wsgi_app(environ, start_response)  File "/var/task/flask/app.py", line 2442, in wsgi_app    ctx = self.request_context(environ)  File "/var/task/flask/app.py", line 2359, in request_context    return RequestContext(self, environ)  File "/var/task/flask/ctx.py", line 292, in __init__    self.url_adapter = app.create_url_adapter(self.request)  File "/var/task/flask/app.py", line 2171, in create_url_adapter    return self.url_map.bind_to_environ(  File "/var/task/werkzeug/routing.py", line 1594, in bind_to_environ    wsgi_server_name = get_host(environ).lower()  File "/var/task/werkzeug/wsgi.py", line 168, in get_host    rv = environ["SERVER_NAME"] | [ERROR] KeyError: 'SERVER_NAME' Traceback (most recent call last):   File "/var/task/flask_lambda.py", line 97, in __call__     return super(FlaskLambda, self).__call__(event, context)   File "/var/task/flask/app.py", line 2464, in __call__     return self.wsgi_app(environ, start_response)   File "/var/task/flask/app.py", line 2442, in wsgi_app     ctx = self.request_context(environ)   File "/var/task/flask/app.py", line 2359, in request_context     return RequestContext(self, environ)   File "/var/task/flask/ctx.py", line 292, in __init__     self.url_adapter = app.create_url_adapter(self.request)   File "/var/task/flask/app.py", line 2171, in create_url_adapter     return self.url_map.bind_to_environ(   File "/var/task/werkzeug/routing.py", line 1594, in bind_to_environ     wsgi_server_name = get_host(environ).lower()   File "/var/task/werkzeug/wsgi.py", line 168, in get_host     rv = environ["SERVER_NAME"]
-- | --

**Comment by CodeSchwert** [comment]
Are you using an HTTP API or Rest API? 

I got the same error when switching from a REST API to HTTP API.

**Comment by bhaveshachhada** [comment]
Any updates on this ? I also got the same error.
